[tool.poetry]
name = "playwright-project"
version = "0.0.5"
description = "After this course i will be a decent playwright and pytest developer"
authors = ["Jean Kobeis <johnny_kobeis@live.com>"]
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3"
]

[tool.poetry.dependencies]
python = "^3.11 <= 3.11.6"
playwright = "^1.38.0"
cisco-sdwan = "^1.21.3"


[tool.poetry.group.dev.dependencies]
pytest-playwright = "^0.4.3"
pytest-xdist = "^3.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Home Page" = "https://github.com/jeankobeis/playwrights"
"Bug Tracker" = "https://github.com/jeankobeis/playwrights/issues"

[tool.poetry.scripts]
playwrights_tuts = "playwrights.__main__:main"
