[project]
name = "hf-argparser"
version = "0.1.0"
description = "Standalone version of the HuggingFace ArgParser from the Transformers library"
authors = [{ name = "John Henning", email = "john@henning.ai" }]
dependencies = [
    "pyyaml>=6.0.1",
]
requires-python = ">=3.9"
readme = "README.md"
license = "Apache-2.0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pdm.dev-dependencies]
dev = ["ruff>=0.0.292", "black>=23.9.1"]

[tool.black]
line-length = 119
target-version = ['py39']

[tool.ruff]
ignore = ["C901", "E501", "E741"]
select = ["C", "E", "F", "I", "W"]
line-length = 119

[tool.ruff.isort]
lines-after-imports = 2
known-first-party = ["hf_argparser"]
