[project]
name = "aioka"
version = "0.1.1-dev"
description = "aio-pika framework"
authors = [
    { name = "Chebotarev Victor", email = "powersemmi@gmail.com" },
]
dependencies = [
    "aio-pika>=9.3.0",
    "pytz>=2023.3.post1",
    "pydantic>=2.4.2",
    "uvicorn[standart]>=0.23.2",
]
requires-python = ">=3.11"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.4.2",
    "isort>=5.12.0",
    "flake8-pyproject>=1.2.3",
    "black>=23.9.1",
]

[tool.pdm.resolution]
respect-source-order = true

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.flake8]
ignore = [
    "W291",
    "E203",
]
exclude = [
    ".git",
    "__pycache__",
    "docs",
    "build",
    "dist",
    ".venv",
    "venv",
    "__pypackages__",
]
per-file-ignores = "__init__.py:F401"
max-line-length = 79
count = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
