[tool.poetry]
authors = ["Daniel CAUNE <daniel@bootloader.studio>"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries",
]
description = "Repository of reusable Python components to be shared by Python projects using the Bootloader services"
include = [
    "CHANGELOG.md",
]
keywords = ["core", "library"]
license = "SEE LICENSE IN <LICENSE.md>"
name = "bootloader-core-library"
packages = [{include = "bootloader", from = "src"}]
readme = "README.md"
repository = "https://github.com/bootloader-studio/bootloader-core-python-library"
version = "0.0.28"

[tool.poetry.dependencies]
perseus-core-library = "^1.19.7"
python = "^3.10"
setuptools = "^68.2.2"

[tool.poetry.group.dev.dependencies]
setuptools = "^68.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
