[tool.poetry]
name = "backup-github-org"
version = "1.0.10"
description = ""
authors = ["Karina5005 <karinaanisimova23062001@gmail.com>"]
readme = "README.md"
packages = [{include = "backup_github"}]

[tool.poetry.dependencies]
python = "^3.8.1"
requests = "^2.28.2"
prometheus_client = "^0.16.0"


[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
black = "^23.1.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
requests-mock = "^1.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
backup-github = "backup_github.main:main"
