[project]
name = "apidag"
version = "0.1.1"
authors = [
  { name="Sarahhhh", email="sarahhhhfoster@gmail.com" },
]
description = "A Python library using asyncio and aiohttp to build declarative API call flows"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  'aiohttp >= 3.8.4, < 4',
  'jsonpath_ng >= 1.6.0, < 2',
  'networkx >= 3.0rc1, < 4',
]

[project.urls]
"Homepage" = "https://github.com/SarahhhhFoster/apidag"
"Bug Tracker" = "https://github.com/SarahhhhFoster/apidag/issues"