[project]
name = "request_manager_attenuare"
version = "0.0.3"
authors = [
  { name="Leandro Alves", email="leandro.augusto.alves@outlook.com.br" },
]
description = "Class used to manage a specific request to a endpoint, and try again if specific errors appear"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Attenuare/request_manager"
