[tool.poetry]
name = "not-found-404"
version = "0.1.3"
description = ""
authors = ["Aziz Rahman Yarzai <azizulrahman.yarzai@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
