[ tool.poetry ]

name            = "py-objects"
version         = "0.1.0"
description     = "Better Than Enums"
authors         = [ "Ofer Nave <odigity@gmail.com>" ]
readme          = "README.md"
repository      = "https://github.com/odigity/py-objects/"
documentation   = "https://py-objects.readthedocs.io/en/latest/"
packages        = [ { include = "objects" } ]


[ tool.poetry.urls ]

changelog       = "https://github.com/odigity/py-objects/blob/master/CHANGELOG.md"


[ tool.poetry.dependencies ]

python          = "^3.7"


[ tool.poetry.group.dev.dependencies ]

pytest          = "^7"


[ tool.pytest.ini_options ]

addopts   = [ "--capture=no", "--color=yes", "--import-mode=importlib" ]
markers   = [ "only" ]      # useful during development (`@pytest.mark.only` + `pytest -m only`)
testpaths = [ "tests" ]


[ build-system ]

requires        = [ "poetry-core" ]
build-backend   = "poetry.core.masonry.api"
