[tool.poetry]
name = "bl-event-sourcing"
version = "0.2.2"
description = "Event sourcing library"
authors = ["Tanguy Le Carrour <tanguy@bioneland.org>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://git.easter-eggs.org/bioneland/bl-event-sourcing"
repository = "https://git.easter-eggs.org/bioneland/bl-event-sourcing"

exclude = ["**/*_spec.py"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
invoke = "^1.6.0"
black = "^22.3.0"
isort = "^5.9.2"
flake8 = "^4.0.1"
safety = "^1.10.3"
termcolor = "^1.1.0"
mypy = "^0.961"
types-mock = "^4.0.15"
types-setuptools = "^57.0.0"
mamba = "^0.11.2"
robber = "^1.1.5"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
line-length = 89

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
