[tool.poetry]
name = "horsetalk"
version = "0.21.0"
description = "A library of enums and parsers for common horseracing terminology"
authors = ["peaky76 <robertjamespeacock@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
measurement = "^3.2.2"
peak-utility = "~0"
pendulum = "^2.1.2"

[tool.poetry.group.dev.dependencies]
auto-changelog = "^0.6.0"
black = "^23.3.0"
coverage = "^7.2.2"
mypy = "^1.1.1"
pytest = "^7.2.2"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
sphinx = ">=6.1.3,<8.0.0"
sphinx-rtd-theme = "^1.2.0"
ruff = ">=0.0.261,<0.0.293"
radon = "^6.0.1"

[tool.ruff]
ignore = ["E501", "E741", "F821"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
