[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "msgraph-py"
version = "0.1.1"
dependencies = ["requests"]
authors = [
  { name="Feda Merdzanovic", email="feda@merdzanovic.com" },
]
description = "Collection of functions for easily using Microsoft Graph API in Python."
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]