[project]
name = "flinkdrain3"
version = "0.0.3"
authors = [
  { name="NITROGENousFish", email="lizongyang0527@hotmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.7"
jsonpickle = "*"
cachetools = "*"

[project.urls]
"Homepage" = "https://github.com/NITROGENousFish/flinkdrain3"
"Bug Tracker" = "https://github.com/NITROGENousFish/flinkdrain3/issues"