[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sqlite3-simple-orm"
version = "0.2"
authors = [
  { name="Борисенко Лень", email="pzrnqt1vrss@protonmail.com" },
]
description = "Простой orm для sqlite3"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[project.urls]
"Homepage" = "https://github.com/leo-need-more-coffee/simple-orm"
"Bug Tracker" = "https://github.com/leo-need-more-coffee/simple-orm/issues"
