[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "terraclip"
version = "1.0b2"
authors = [
  { name="Rodrigo Nascimento Hernandez", email="rodrigomdev@gmail.com" },
]
description = "Anti-collision Ardupilot terrain following mission generator."
readme = "README.md"
requires-python = ">=3.1"
dependencies = [
	'numpy',
	'gdalwrap',
	'requests',
	'certifi',
	]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: IPython",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: GIS",
]

[tool.hatch.build.targets.wheel]
packages = ["src/terraclip",]

[project.urls]
"Homepage" = "https://github.com/Rodrigo-NH/Terraclip"
"Bug Tracker" = "https://github.com/Rodrigo-NH/Terraclip/issues"

