[tool.poetry]
name = "docker-secrets-dotenv"
version = "0.1.2"
description = "Load docker secrets into ENV"
authors = ["Richard Soper"]
license = "MIT"
readme = "README.md"
packages = [{include = "docker_secrets"}]
repository = "https://gitlab.richardsoper.me/richardsoper/docker-secrets"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
